// frontend/src/courseData.js
const allCourses = [
    { "courseCode": "BCHY101L", "courseTitle": "Engineering Chemistry" },
    { "courseCode": "BCHY101P", "courseTitle": "Engineering Chemistry Lab" },
    { "courseCode": "BMAT101L", "courseTitle": "Calculus" },
    { "courseCode": "BMAT101P", "courseTitle": "Calculus Lab" },
    { "courseCode": "BMAT102L", "courseTitle": "Differential Equations and Transforms" },
    { "courseCode": "BMAT201L", "courseTitle": "Complex Variables and Linear Algebra" },
    { "courseCode": "BMAT202L", "courseTitle": "Probability and Statistics" },
    { "courseCode": "BMAT202P", "courseTitle": "Probability and Statistics Lab" },
    { "courseCode": "BPHY101L", "courseTitle": "Engineering Physics" },
    { "courseCode": "BPHY101P", "courseTitle": "Engineering Physics Lab" },
    { "courseCode": "BCSE101E", "courseTitle": "Computer Programming: Python" },
    { "courseCode": "BCSE102L", "courseTitle": "Structured and Object-Oriented Programming" },
    { "courseCode": "BCSE102P", "courseTitle": "Structured and Object-Oriented Programming Lab" },
    { "courseCode": "BCSE103E", "courseTitle": "Computer Programming: Java" },
    { "courseCode": "BEEE102L", "courseTitle": "Basic Electrical and Electronics Engineering" },
    { "courseCode": "BEEE102P", "courseTitle": "Basic Electrical and Electronics Engineering Lab" },
    { "courseCode": "BENG101L", "courseTitle": "Technical English Communication" },
    { "courseCode": "BENG101P", "courseTitle": "Technical English Communication Lab" },
    { "courseCode": "BENG102P", "courseTitle": "Technical Report Writing" },
    { "courseCode": "BFLE200L", "courseTitle": "Foreign Language" },
    { "courseCode": "BHSM200L", "courseTitle": "HSM Elective" },
    { "courseCode": "BSTS101P", "courseTitle": "Quantitative Skills Practice I" },
    { "courseCode": "BSTS102P", "courseTitle": "Quantitative Skills Practice II" },
    { "courseCode": "BSTS201P", "courseTitle": "Qualitative Skills Practice I" },
    { "courseCode": "BSTS202P", "courseTitle": "Qualitative Skills Practice II" },
    { "courseCode": "BECE102L", "courseTitle": "Digital Systems Design" },
    { "courseCode": "BECE102P", "courseTitle": "Digital Systems Design Lab" },
    { "courseCode": "BECE204L", "courseTitle": "Microprocessors and Microcontrollers" },
    { "courseCode": "BECE204P", "courseTitle": "Microprocessors and Microcontrollers Lab" },
    { "courseCode": "BMAT205L", "courseTitle": "Discrete Mathematics and Graph Theory" },
    { "courseCode": "BCSE202L", "courseTitle": "Data Structures and Algorithms" },
    { "courseCode": "BCSE202P", "courseTitle": "Data Structures and Algorithms Lab" },
    { "courseCode": "BCSE203E", "courseTitle": "Web Programming" },
    { "courseCode": "BCSE204L", "courseTitle": "Design and Analysis of Algorithms" },
    { "courseCode": "BCSE204P", "courseTitle": "Design and Analysis of Algorithms Lab" },
    { "courseCode": "BCSE205L", "courseTitle": "Computer Architecture and Organization" },
    { "courseCode": "BCSE301L", "courseTitle": "Software Engineering" },
    { "courseCode": "BCSE301P", "courseTitle": "Software Engineering Lab" },
    { "courseCode": "BCSE302L", "courseTitle": "Database Systems" },
    { "courseCode": "BCSE302P", "courseTitle": "Database Systems Lab" },
    { "courseCode": "BCSE303L", "courseTitle": "Operating Systems" },
    { "courseCode": "BCSE303P", "courseTitle": "Operating Systems Lab" },
    { "courseCode": "BCSE304L", "courseTitle": "Theory of Computation" },
    { "courseCode": "BCSE305L", "courseTitle": "Embedded Systems" },
    { "courseCode": "BCSE306L", "courseTitle": "Artificial Intelligence" },
    { "courseCode": "BCSE307L", "courseTitle": "Compiler Design" },
    { "courseCode": "BCSE307P", "courseTitle": "Compiler Design Lab" },
    { "courseCode": "BCSE308L", "courseTitle": "Computer Networks" },
    { "courseCode": "BCSE308P", "courseTitle": "Computer Networks Lab" },
    { "courseCode": "BCSE309L", "courseTitle": "Cryptography and Network Security" },
    { "courseCode": "BCSE309P", "courseTitle": "Cryptography and Network Security Lab" },
    { "courseCode": "BCSE206L", "courseTitle": "Foundations of Data Science" },
    { "courseCode": "BCSE207L", "courseTitle": "Programming for Data Science" },
    { "courseCode": "BCSE207P", "courseTitle": "Programming for Data Science Lab" },
    { "courseCode": "BCSE208L", "courseTitle": "Data Mining" },
    { "courseCode": "BCSE208P", "courseTitle": "Data Mining Lab" },
    { "courseCode": "BCSE209L", "courseTitle": "Machine Learning" },
    { "courseCode": "BCSE209P", "courseTitle": "Machine Learning Lab" },
    { "courseCode": "BCSE310L", "courseTitle": "IoT Architectures and Protocols" },
    { "courseCode": "BCSE311L", "courseTitle": "Sensors and Actuator Devices" },
    { "courseCode": "BCSE311P", "courseTitle": "Sensors and Actuator Devices Lab" },
    { "courseCode": "BCSE312L", "courseTitle": "Programming for loT Boards" },
    { "courseCode": "BCSE312P", "courseTitle": "Programming for IoT Boards Lab" },
    { "courseCode": "BCSE313L", "courseTitle": "Fundamentals of Fog and Edge Computing" },
    { "courseCode": "BCSE314L", "courseTitle": "Privacy and Security in IoT" },
    { "courseCode": "BCSE315L", "courseTitle": "Wearable Computing" },
    { "courseCode": "BCSE316L", "courseTitle": "Design of Smart Cities" },
    { "courseCode": "BCSE317L", "courseTitle": "Information Security" },
    { "courseCode": "BCSE318L", "courseTitle": "Data Privacy" },
    { "courseCode": "BCSE319L", "courseTitle": "Penetration Testing and Vulnerability Analysis" },
    { "courseCode": "BCSE319P", courseTitle: "Penetration Testing and Vulnerability Analysis Lab" },
    { "courseCode": "BCSE320L", courseTitle: "Web Application Security" },
    { "courseCode": "BCSE321L", courseTitle: "Malware Analysis" },
    { "courseCode": "BCSE321P", courseTitle: "Malware Analysis Lab" },
    { "courseCode": "BCSE322L", courseTitle: "Digital Forensics" },
    { "courseCode": "BCSE322P", courseTitle: "Digital Forensics Lab" },
    { "courseCode": "BCSE323L", courseTitle: "Digital Watermarking and Steganography" },
    { "courseCode": "BCSE324L", courseTitle: "Foundations of Blockchain Technology" },
    { "courseCode": "BCSE325L", courseTitle: "Introduction to Bitcoin" },
    { "courseCode": "BCSE326L", courseTitle: "Blockchain Architecture Design" },
    { "courseCode": "BCSE327L", courseTitle: "Smart Contracts" },
    { "courseCode": "BCSE327P", courseTitle: "Smart Contracts Lab" },
    { "courseCode": "BCSE328L", courseTitle: "Cryptocurrency Technologies" },
    { "courseCode": "BCSE329L", courseTitle: "Blockchain and Distributed Ledger Technology" },
    { "courseCode": "BCSE329P", courseTitle: "Blockchain and Distributed Ledger Technology Lab" },
    { "courseCode": "BCSE330L", courseTitle: "Public Key Infrastructure and Trust Management" },
    { "courseCode": "BCSE331L", courseTitle: "Exploratory Data Analysis" },
    { "courseCode": "BCSE331P", courseTitle: "Exploratory Data Analysis Lab" },
    { "courseCode": "BCSE332L", courseTitle: "Deep Learning" },
    { "courseCode": "BCSE332P", courseTitle: "Deep Learning Lab" },
    { "courseCode": "BCSE333L", courseTitle: "Statistical Inference" },
    { "courseCode": "BCSE333P", courseTitle: "Statistical Inference Lab" },
    { "courseCode": "BCSE334L", courseTitle: "Predictive Analytics" },
    { "courseCode": "BCSE335L", courseTitle: "Healthcare Data Analytics" },
    { "courseCode": "BCSE336L", courseTitle: "Financial Data Analytics" },
    { "courseCode": "BCSE336P", courseTitle: "Financial Data Analytics Lab" },
    { "courseCode": "BCSE337P", courseTitle: "Embedded System Design Lab" },
    { "courseCode": "BCSE391J", courseTitle: "Technical Answers to Real Problems Project" },
    { "courseCode": "BCSE392J", courseTitle: "Design Project" },
    { "courseCode": "BCSE393J", courseTitle: "Laboratory Project" },
    { "courseCode": "BCSE394J", courseTitle: "Product Development Project" },
    { "courseCode": "BCSE395J", courseTitle: "Computer Project" },
    { "courseCode": "BCSE396J", courseTitle: "Reading Course" },
    { "courseCode": "BCSE397J", courseTitle: "Special Project" },
    { "courseCode": "BCSE398J", courseTitle: "Simulation Project" },
    { "courseCode": "BCSE401L", courseTitle: "Internet of Things" },
    { "courseCode": "BCSE402L", courseTitle: "Big Data Analytics" },
    { "courseCode": "BCSE403L", courseTitle: "Digital Image Processing" },
    { "courseCode": "BCSE405L", courseTitle: "Advanced Java Programming" },
    { "courseCode": "BCSE406L", courseTitle: "NoSQL Databases" },
    { "courseCode": "BCSE407L", courseTitle: "Computer vision" },
    { "courseCode": "BCSE408L", courseTitle: "Cloud Computing" },
    { "courseCode": "BCSE409L", courseTitle: "Natural Language Processing" },
    { "courseCode": "BCSE410L", courseTitle: "Cyber Security" },
    { "courseCode": "BCSE411L", courseTitle: "Robotics and Automation" },
    { "courseCode": "BCSE412L", courseTitle: "Parallel Computing" },
    { "courseCode": "BCSE413L", courseTitle: "Soft computing" },
    { "courseCode": "BCSE414L", courseTitle: "High Performance Computing" },
    { "courseCode": "BCSE415L", courseTitle: "Human Computer Interaction" },
    { "courseCode": "BCSE416L", courseTitle: "Game Programming" },
    { "courseCode": "BCSE416P", courseTitle: "Game Programming Lab" },
    { "courseCode": "BCSE417L", courseTitle: "Machine vision" },
    { "courseCode": "BCSE417P", courseTitle: "Machine Vision Lab" },
    { "courseCode": "BCSE418L", courseTitle: "Explainable Artificial Intelligence" },
    { "courseCode": "BCSE419L", courseTitle: "Speech and Language Processing" },
    { "courseCode": "BCSE419P", courseTitle: "Speech and Language Processing lab" },
    { "courseCode": "BCSE420L", courseTitle: "Sensors, Actuators and Signal Conditioning" },
    { "courseCode": "BCSE420P", courseTitle: "Sensors, Actuators and Signal Conditioning Lab" },
    { "courseCode": "BCSE421L", courseTitle: "Robotics: Kinematics, Dynamics and Motion Control" },
    { "courseCode": "BCSE422L", courseTitle: "Robot Modeling and Simulation" },
    { "courseCode": "BCSE422P", courseTitle: "Robot Modeling and Simulation Lab" },
    { "courseCode": "BCSE423L", courseTitle: "Robot Programming" },
    { "courseCode": "BCSE423P", courseTitle: "Robot Programming Lab" },
    { "courseCode": "BCSE424L", courseTitle: "Machine Learning for Robotics" },
    { "courseCode": "BCSE424P", courseTitle: "Machine Learning for Robotics Lab" },
    { "courseCode": "BCSE425L", courseTitle: "Robotic Perception" },
    { "courseCode": "BCSE425P", courseTitle: "Robotic Perception Lab" },
    { "courseCode": "BCSE426L", courseTitle: "Robotic Process Automation" },
    { "courseCode": "BCSE426P", courseTitle: "Robotic Process Automation Lab" },
    { "courseCode": "BCSE427L", courseTitle: "Cognitive Robotics" },
    { "courseCode": "BCSE427P", courseTitle: "Cognitive Robotics Lab" },
    { "courseCode": "BCSE428L", courseTitle: "Autonomous Drones" },
    { "courseCode": "BCSE428P", courseTitle: "Autonomous Drones Lab" },
    { "courseCode": "BCSE429L", courseTitle: "Cyber Physical Systems Design" },
    { "courseCode": "BCSE429P", courseTitle: "Cyber Physical System Design Lab" },
    { "courseCode": "BCSE430L", courseTitle: "Distributed Real Time Systems" },
    { "courseCode": "BCSE430P", courseTitle: "Distributed Real Time Systems Lab" },
    { "courseCode": "BCSE431L", courseTitle: "Fundamentals of Quantum Computing" },
    { "courseCode": "BCSE432E", courseTitle: "Reinforcement Learning" },
    { "courseCode": "BECM302E", courseTitle: "Augmented and Virtual Reality" },
    { "courseCode": "BEEE303L", courseTitle: "Control Systems" },
    { "courseCode": "BEEE303P", courseTitle: "Control Systems Lab" },
    { "courseCode": "BCSE399J", courseTitle: "Summer Industrial Internship" },
    { "courseCode": "BCSE497J", courseTitle: "Project-1" },
    { "courseCode": "BCSE498J", courseTitle: "Project II/Internship" },
    { "courseCode": "BCSE499J", courseTitle: "One Semester Internship" },
    { "courseCode": "BCSE353E", courseTitle: "Information Security Analysis and Audit" },
    { "courseCode": "BCSE354E", courseTitle: "Information Security Management" },
    { "courseCode": "BCSE355L", courseTitle: "Cloud Architecture Design" },
    { "courseCode": "BECE201L", courseTitle: "Electronic Materials and devices" },
    { "courseCode": "BECE203L", courseTitle: "Circuit Theory" },
    { "courseCode": "BEEE203L", courseTitle: "Circuit Theory" },
    { "courseCode": "BEEE206L", courseTitle: "Digital Electronics" },
    { "courseCode": "BEEE206P", courseTitle: "Digital Electronics Lab" },
    { "courseCode": "BFST213E", courseTitle: "Garment Designing and Manufacturing" },
    { "courseCode": "BHUM110L", courseTitle: "Cognitive Psychology" },
    { "courseCode": "BHUM111L", courseTitle: "Happiness and Wellbeing-" },
    { "courseCode": "BHUM112L", courseTitle: "Social Psychology" },
    { "courseCode": "BHUM114L", courseTitle: "International Economic Relations" },
    { "courseCode": "BHUM201L", courseTitle: "Mass Cornmunication" },
    { "courseCode": "BHUM202L", courseTitle: "Rural Development" },
    { "courseCode": "BHUM203L", courseTitle: "Introduction to Psychology" },
    { "courseCode": "BHUM204L", courseTitle: "Industrial Psychology" },
    { "courseCode": "BHUM205L", courseTitle: "Development Economics" },
    { "courseCode": "BHUM206L", courseTitle: "International Economics" },
    { "courseCode": "BHUM207L", courseTitle: "Engineering Economics" },
    { "courseCode": "BHUM208L", courseTitle: "Economics of Strategy" },
    { "courseCode": "BHUM209L", courseTitle: "Game Theory" },
    { "courseCode": "BHUM210E", courseTitle: "Econometrics" },
    { "courseCode": "BHUM211L", courseTitle: "Behavioral Economics" },
    { "courseCode": "BHUM212L", courseTitle: "Mathematics for Economic Analysis" },
    { "courseCode": "BHUM213L", courseTitle: "Corporate Social Responsibility" },
    { "courseCode": "BHUM214L", courseTitle: "Political Science" },
    { "courseCode": "BHUM215L", courseTitle: "International Relations" },
    { "courseCode": "BHUM216L", courseTitle: "Indian Culture and Heritage" },
    { "courseCode": "BHUM217L", courseTitle: "Contemporary India" },
    { "courseCode": "BHUM218L", courseTitle: "Financial Management" },
    { "courseCode": "BHUM219L", courseTitle: "Principles of Accounting" },
    { "courseCode": "BHUM220L", courseTitle: "Financial Markets and Institutions" },
    { "courseCode": "BHUM221L", courseTitle: "Economics of Money, Banking and Financial Markets" },
    { "courseCode": "BHUM222L", courseTitle: "Security Analysis and Portfolio Management" },
    { "courseCode": "BHUM223L", courseTitle: "Options, Futures and other Derivatives" },
    { "courseCode": "BHUM224L", courseTitle: "Fixed Income Securities" },
    { "courseCode": "BHUM225L", courseTitle: "Personal Finance" },
    { "courseCode": "BHUM226L", courseTitle: "Corporate Finance" },
    { "courseCode": "BHUM227L", courseTitle: "Financial Statement Analysis" },
    { "courseCode": "BHUM228L", courseTitle: "Cost and Management Accounting" },
    { "courseCode": "BHUM231L", courseTitle: "Reproductive choices for a Sustainable Society" },
    { "courseCode": "BHUM232L", courseTitle: "Introduction to Sustainable Aging" },
    { "courseCode": "BHUM233L", courseTitle: "Environmental Psychology" },
    { "courseCode": "BHUM234L", courseTitle: "Indian Psychology" },
    { "courseCode": "BHUM235E", courseTitle: "Psychology of Wellness" },
    { "courseCode": "BHUM236L", courseTitle: "Taxation" },
    { "courseCode": "BMEE102P", courseTitle: "Engineering Design Visualisation Lab" },
    { "courseCode": "BMEE355E", courseTitle: "Cloud Computing" },
    { "courseCode": "BSTS301P", courseTitle: "Advanced Competitive Coding - 1" },
    { "courseCode": "BSTS302P", courseTitle: "Advanced Competitive Coding - II" },
    { "courseCode": "CFOC101M", courseTitle: "Advanced Green Manufacturing Systems" },
    { "courseCode": "CFOC102M", courseTitle: "Introduction to Cognitive Psychology" },
    { "courseCode": "CFOC103M", courseTitle: "Introduction to Political Theory" },
    { "courseCode": "CFOC104M", courseTitle: "Six Sigma" },
    { "courseCode": "CFOC105M", courseTitle: "Emotional Intelligence" },
    { "courseCode": "CFOC106M", courseTitle: "Manufacturing Strategy" },
    { "courseCode": "CFOC107M", courseTitle: "Supply Chain Analytics" },
    { "courseCode": "CFOC108M", courseTitle: "Systems Engineering: Theory and Practice" },
    { "courseCode": "CFOC109M", courseTitle: "Design Thinking - A Primer" },
    { "courseCode": "CFOC110M", courseTitle: "MCDM Techniques Using R and MARLAB" },
    { "courseCode": "CFOC111M", courseTitle: "Perspectives on Neurolinguistic" },
    { "courseCode": "CFOC112M", courseTitle: "Sociology of Science" },
    { "courseCode": "CFOC113M", courseTitle: "Contemporary Themes in India’s Economic Development and Economic Survey" },
    { "courseCode": "CFOC114M", courseTitle: "Problem Solving through Programming in C" },
    { "courseCode": "CFOC115M", courseTitle: "Design and Analysis of Algorithms" },
    { "courseCode": "CFOC116M", courseTitle: "Computer Vision" },
    { "courseCode": "CFOC117M", courseTitle: "Spatial Informatics" },
    { "courseCode": "CFOC118M", courseTitle: "Practical Machine Learning with Tensorflow" },
    { "courseCode": "CFOC119M", courseTitle: "Training of Trainers" },
    { "courseCode": "CFOC120M", courseTitle: "Knowledge Management" },
    { "courseCode": "CFOC121M", courseTitle: "Leadership" },
    { "courseCode": "CFOC122M", courseTitle: "Educational Leadership" },
    { "courseCode": "CFOC123M", courseTitle: "Cost Accounting" },
    { "courseCode": "CFOC124M", courseTitle: "Practitioners Course In Descriptive, Predictive and Prescriptive Analytics" },
    { "courseCode": "CFOC125M", courseTitle: "Decision Making Under Uncertainty" },
    { "courseCode": "CFOC126M", courseTitle: "Data Analysis and Decision Making - III" },
    { "courseCode": "CFOC127M", courseTitle: "Business Analytics and Data Mining Modeling Using R Part II" },
    { "courseCode": "CFOC128M", courseTitle: "Business Analytics and Text Mining Modeling Using Python" },
    { "courseCode": "CFOC129M", courseTitle: "Economics of Health and Health Care" },
    { "courseCode": "CFOC130M", courseTitle: "Human Resource Development" },
    { "courseCode": "CFOC131M", courseTitle: "Performance and Reward Management" },
    { "courseCode": "CFOC132M", courseTitle: "Corporate Social Responsibility" },
    { "courseCode": "CFOC133M", courseTitle: "E-Business" },
    { "courseCode": "CFOC134M", courseTitle: "Innovation, Business Models and Entrepreneurship" },
    { "courseCode": "CFOC135M", courseTitle: "The Ethical Corporation" },
    { "courseCode": "CFOC136M", courseTitle: "Toyota Production System" },
    { "courseCode": "CFOC137M", courseTitle: "Intellectual Property Rights and Competition Law" },
    { "courseCode": "CFOC138M", courseTitle: "Patent Search for Engineers and Lawyers" },
    { "courseCode": "CFOC139M", courseTitle: "Role of Craft and Technology in Interior Architecture" },
    { "courseCode": "CFOC140M", courseTitle: "Glass In Buildings: Design And Applications" },
    { "courseCode": "CFOC141M", courseTitle: "Visual Perception and Art: A Survey Across the Cultures" },
    { "courseCode": "CFOC142M", courseTitle: "Mapping Signal Processing Algorithms to Architectures" },
    { "courseCode": "CFOC143M", courseTitle: "Introduction to Computer Vision" },
    { "courseCode": "CFOC144M", courseTitle: "Op-Amp Practical Applications: Design, Simulation and Implementation" },
    { "courseCode": "CFOC145M", courseTitle: "Fabrication Techniques for MEMs - based sensors: clinical Perspective" },
    { "courseCode": "CFOC146M", courseTitle: "Linear System Theory" },
    { "courseCode": "CFOC147M", courseTitle: "Advanced Linear Continuous Control Systems: Applications with MATLAB Programming and Simulink" },
    { "courseCode": "CFOC148M", courseTitle: "Introduction to Wireless and Cellular Communications" },
    { "courseCode": "CFOC149M", courseTitle: "Digital Switching - 1" },
    { "courseCode": "CFOC150M", courseTitle: "Microelectronics: Devices To Circuits" },
    { "courseCode": "CFOC151M", courseTitle: "Digital Image Processing" },
    { "courseCode": "CFOC152M", courseTitle: "Pattern Recognition and Application" },
    { "courseCode": "CFOC153M", courseTitle: "Microwave Theory and Techniques" },
    { "courseCode": "CFOC154M", courseTitle: "Principles and Techniques of Modern Radar Systems" },
    { "courseCode": "CFOC155M", courseTitle: "Computational Electromagnetics" },
    { "courseCode": "CFOC156M", courseTitle: "Microwave Engineering" },
    { "courseCode": "CFOC157M", courseTitle: "Introduction to parallel Programming in Open MP" },
    { "courseCode": "CFOC158M", courseTitle: "Reinforcement Learning" },
    { "courseCode": "CFOC159M", courseTitle: "Applied Natural Language Processing" },
    { "courseCode": "CFOC160M", courseTitle: "Python for Data Science" },
    { "courseCode": "CFOC161M", courseTitle: "Data Science for Engineers" },
    { "courseCode": "CFOC162M", courseTitle: "Scalable Data Science" },
    { "courseCode": "CFOC163M", courseTitle: "Advanced Computer Architecture" },
    { "courseCode": "CFOC164M", courseTitle: "Software Project Management" },
    { "courseCode": "CFOC165M", courseTitle: "Software testing" },
    { "courseCode": "CFOC166M", courseTitle: "Hardware Modeling using Verilog" },
    { "courseCode": "CFOC167M", courseTitle: "Synthesis of Digital Systems" },
    { "courseCode": "CFOC168M", courseTitle: "Switching Circuits and Logic Design" },
    { "courseCode": "CFOC169M", courseTitle: "Demystifying networking" },
    { "courseCode": "CFOC170M", courseTitle: "Modern Algebra" },
    { "courseCode": "CFOC171M", courseTitle: "Introduction to Haskell Programming 2" },
    { "courseCode": "CFOC172M", courseTitle: "Flow through Porous Media" },
    { "courseCode": "CFOC173M", courseTitle: "Bioenergy" },
    { "courseCode": "CFOC174M", courseTitle: "Introduction to Biostatistics" },
    { "courseCode": "CFOC175M", courseTitle: "Nanotechnology in Agriculture" },
    { "courseCode": "CFOC176M", courseTitle: "Computer Aided Drug Design" },
    { "courseCode": "CFOC177M", courseTitle: "Drug Delivery: Principles and Engineering" },
    { "courseCode": "CFOC178M", courseTitle: "Functional Genomics" },
    { "courseCode": "CFOC179M", courseTitle: "Introduction to Proteogenomics" },
    { "courseCode": "CFOC180M", courseTitle: "Introduction to Mechanobiology" },
    { "courseCode": "CFOC181M", courseTitle: "WildLife Conservation" },
    { "courseCode": "CFOC182M", courseTitle: "Organic Chemistry in Biology and Drug Development" },
    { "courseCode": "CFOC183M", courseTitle: "Bioinorganic Chemistry" },
    { "courseCode": "CFOC184M", courseTitle: "Spectroscopic Techniques for Pharmaceutical and Biopharmaceutical Industries" },
    { "courseCode": "CFOC185M", courseTitle: "Biophysical chemistry" },
    { "courseCode": "CFOC186M", courseTitle: "Deep Learning" },
    { "courseCode": "CFOC187M", courseTitle: "Blockchain Architecture Design and use Cases" },
    { "courseCode": "CFOC188M", courseTitle: "Ethical Hacking" },
    { "courseCode": "CFOC189M", courseTitle: "Organic Farming for Sustainable Agricultural Production" },
    { "courseCode": "CFOC190M", courseTitle: "Positive Psychology" },
    { "courseCode": "CFOC191M", courseTitle: "Forests and their Management" },
    { "courseCode": "CFOC192M", courseTitle: "Forest Biometry" },
    { "courseCode": "CFOC193M", courseTitle: "Bioengineering: An Interface with Biology and Medicine" },
    { "courseCode": "CFOC194M", courseTitle: "Human Molecular Genetics" },
    { "courseCode": "CFOC195M", courseTitle: "Bioenergetics of Life Processes" },
    { "courseCode": "CFOC196M", courseTitle: "Computational Systems Biology" },
    { "courseCode": "CFOC197M", courseTitle: "Bio-Informatics: Algorithms and Applications" },
    { "courseCode": "CFOC198M", courseTitle: "Biostatistics and Design of Experiments" },
    { "courseCode": "CFOC199M", courseTitle: "Medical Biomaterials" },
    { "courseCode": "CFOC200M", courseTitle: "Demystifying the Brain" },
    { "courseCode": "CFOC201M", courseTitle: "Principles and Applications of NMR Spectroscopy" },
    { "courseCode": "CFOC202M", courseTitle: "Cell Culture Technologies" },
    { "courseCode": "CFOC203M", courseTitle: "Natural Hazards" },
    { "courseCode": "CFOC204M", courseTitle: "Modern Construction Materials" },
    { "courseCode": "CFOC205M", courseTitle: "Energy Efficiency, Acoustics and Daylighting in Building" },
    { "courseCode": "CFOC206M", courseTitle: "Fire Protection, Services and Maintenance Management of Building" },
    { "courseCode": "CFOC207M", courseTitle: "Electronic Waste Management - Issues And Challenges" },
    { "courseCode": "CFOC208M", courseTitle: "Higher Surveying" },
    { "courseCode": "CFOC209M", courseTitle: "Environmental Remediation of Contaminated Sites" },
    { "courseCode": "CFOC210M", courseTitle: "Soil Structure Interaction" },
    { "courseCode": "CFOC211M", courseTitle: "Introduction to Accounting and Finance for Civil Engineers" },
    { "courseCode": "CFOC212M", courseTitle: "Scheduling Techniques in Projects" },
    { "courseCode": "CFOC213M", courseTitle: "GPS Surveying" },
    { "courseCode": "CFOC214M", courseTitle: "Sustainable Materials and Green Buildings" },
    { "courseCode": "CFOC215M", courseTitle: "Geomorphic Processes: Landforms and Landscapes" },
    { "courseCode": "CFOC216M", courseTitle: "Introduction To Process Modeling in the Membrane Separation Process" },
    { "courseCode": "CFOC217M", courseTitle: "Computational Geometry" },
    { "courseCode": "CFOC218M", courseTitle: "Compiler Design" },
    { "courseCode": "CFOC219M", courseTitle: "Embedded System Design with ARM" },
    { "courseCode": "CFOC220M", courseTitle: "VLSI Physical Design" },
    { "courseCode": "CFOC221M", courseTitle: "Cloud computing" },
    { "courseCode": "CFOC222M", courseTitle: "Artificial Intelligence: Knowledge Representation And Reasoning" },
    { "courseCode": "CFOC223M", courseTitle: "Privacy and Security in Online Social Media" },
    { "courseCode": "CFOC224M", courseTitle: "Information Security - 5 Secure Systems Engineering" },
    { "courseCode": "CFOC225M", courseTitle: "Model Checking" },
    { "courseCode": "CFOC226M", courseTitle: "Randomized Algorithms" },
    { "courseCode": "CFOC227M", courseTitle: "GPU Architectures and Programming" },
    { "courseCode": "CFOC228M", courseTitle: "Multi-Core Computer Architecture - Storage and Interconnects" },
    { "courseCode": "CFOC229M", courseTitle: "Data Analytics with Python" },
    { "courseCode": "CFOC230M", courseTitle: "Arithmetic Circuit Complexity" },
    { "courseCode": "CFOC231M", courseTitle: "Google Cloud Computing Foundation Course" },
    { "courseCode": "CFOC232M", courseTitle: "Consumer Behaviour" },
    { "courseCode": "CFOC233M", courseTitle: "Enhancing Soft Skills and Personality" },
    { "courseCode": "CFOC234M", courseTitle: "Introduction to Airplane Performance" },
    { "courseCode": "CFOC235M", courseTitle: "Rocket Propulsion" },
    { "courseCode": "CFOC236M", courseTitle: "Aircraft Maintenance" },
    { "courseCode": "CFOC237M", courseTitle: "Sustainable Architecture" },
    { "courseCode": "CFOC238M", courseTitle: "Introduction to History of Architecture in India" },
    { "courseCode": "CFOC239M", courseTitle: "Structure, Form, and Architecture: The Synergy" },
    { "courseCode": "CFOC240M", courseTitle: "Interactomics: Basics and Applications" },
    { "courseCode": "CFOC241M", courseTitle: "Introduction to Professional Scientific Communication" },
    { "courseCode": "CFOC242M", courseTitle: "Material and Energy Balances" },
    { "courseCode": "CFOC243M", courseTitle: "Thermodynamics for Biological Systems: Classical and Statistical Aspect" },
    { "courseCode": "CFOC244M", courseTitle: "Optical Spectroscopy and Microscopy: Fundamentals of Optical Measurements and Instrumentation" },
    { "courseCode": "CFOC245M", courseTitle: "Fundamentals of Serniconductor Devices" },
    { "courseCode": "CFOC246M", courseTitle: "Characterization of Construction Materials" },
    { "courseCode": "CFOC247M", courseTitle: "Introduction to Civil Engineering Profession" },
    { "courseCode": "CFOC248M", courseTitle: "Environmental Geomechanics" },
    { "courseCode": "CFOC249M", courseTitle: "Mechanical Characterization of Bituminous Materials" },
    { "courseCode": "CFOC250M", courseTitle: "Geosynthetics and Reinforced Soil Structures" },
    { "courseCode": "CFOC251M", courseTitle: "Geotechnical Engineering II Foundation Engineering" },
    { "courseCode": "CFOC252M", courseTitle: "Landscape Architecture and Site Planning - Basic Fundamentals" },
    { "courseCode": "CFOC253M", courseTitle: "Plastic Waste Management" },
    { "courseCode": "CFOC254M", courseTitle: "Advanced Topics in the Science and Technology of Concrete" },
    { "courseCode": "CFOC255M", courseTitle: "Applied Environmental Microbiology" },
    { "courseCode": "CFOC256M", courseTitle: "Digital Land Surveying And Mapping (DLS&M)" },
    { "courseCode": "CFOC257M", courseTitle: "Earthquake Geology: A tool for Seismic Hazard Assessment" },
    { "courseCode": "CFOC258M", courseTitle: "Introduction to Geographic Information Systems" },
    { "courseCode": "CFOC259M", courseTitle: "Structural Dynamics" },
    { "courseCode": "CFOC260M", courseTitle: "Water Supply Engineering" },
    { "courseCode": "CFOC261M", courseTitle: "Geo Spatial Analysis in Urban Planning" },
    { "courseCode": "CFOC262M", courseTitle: "Geotechnical Engineering - 1" },
    { "courseCode": "CFOC263M", courseTitle: "Maintenance and Repair of Concrete Structures" },
    { "courseCode": "CFOC264M", courseTitle: "Thermodynamics" },
    { "courseCode": "CFOC265M", courseTitle: "Geomorphology" },
    { "courseCode": "CFOC266M", courseTitle: "Remote Sensing Essentials" },
    { "courseCode": "CFOC267M", courseTitle: "Hydraulic Engineering" },
    { "courseCode": "CFOC268M", courseTitle: "Environmental Quality Monitoring and Analysis" },
    { "courseCode": "CFOC269M", courseTitle: "Electrochemical Technology in Pollution Control" },
    { "courseCode": "CFOC270M", courseTitle: "Advanced Thermodynamics" },
    { "courseCode": "CFOC271M", courseTitle: "Membrane Technology" },
    { "courseCode": "CFOC272M", courseTitle: "Computational Fluid Dynamics" },
    { "courseCode": "CFOC273M", courseTitle: "Transport phenomena" },
    { "courseCode": "CFOC274M", courseTitle: "Optimization in Chemical Engineering" },
    { "courseCode": "CFOC275M", courseTitle: "Soft Nano Technology" },
    { "courseCode": "CFOC276M", courseTitle: "Transport processes - Heat and Mass Transfer" },
    { "courseCode": "CFOC277M", courseTitle: "Process Control - Design, Analysis and Assessment" },
    { "courseCode": "CFOC278M", courseTitle: "Heat Transfer" },
    { "courseCode": "CFOC279M", courseTitle: "Chemical Reaction Engineering II" },
    { "courseCode": "CFOC280M", courseTitle: "Multiphase Flows" },
    { "courseCode": "CFOC281M", courseTitle: "Mass Transfer Operations - I" },
    { "courseCode": "CFOC282M", courseTitle: "Waste to Energy Conversion" },
    { "courseCode": "CFOC283M", courseTitle: "Equipment Design: Mechanical Aspects" },
    { "courseCode": "CFOC284M", courseTitle: "An Introduction to Cardiovascular Fluid Mechanics" },
    { "courseCode": "CFOC285M", courseTitle: "Computer Aided Applied Single Objective Optimization" },
    { "courseCode": "CFOC286M", courseTitle: "Basic Principles and Calculations in Chemical Engineering" },
    { "courseCode": "CFOC287M", courseTitle: "Introduction to Blockchain Technology and Applications" },
    { "courseCode": "CFOC288M", courseTitle: "Foundations of Cryptography" },
    { "courseCode": "CFOC289M", courseTitle: "Introduction to Database Systems" },
    { "courseCode": "CFOC290M", courseTitle: "Operating System" },
    { "courseCode": "CFOC291M", courseTitle: "Programming in C++" },
    { "courseCode": "CFOC292M", courseTitle: "Programming in Java" },
    { "courseCode": "CFOC293M", courseTitle: "Data Base Management System" },
    { "courseCode": "CFOC294M", courseTitle: "Introduction to Algorithms and Analysis" },
    { "courseCode": "CFOC295M", courseTitle: "Data Mining" },
    { "courseCode": "CFOC296M", courseTitle: "Embedded Systems Design" },
    { "courseCode": "CFOC297M", courseTitle: "Real Time Operating System" },
    { "courseCode": "CFOC298M", courseTitle: "Introduction to Soft Computing" },
    { "courseCode": "CFOC299M", courseTitle: "Cryptography and Network Security" },
    { "courseCode": "CFOC300M", courseTitle: "Introduction to Internet of Things" },
    { "courseCode": "CFOC301M", courseTitle: "Computer Networks and Internet Protocol" },
    { "courseCode": "CFOC302M", courseTitle: "Introduction to Industry 4.0 and Industrial Internet of Things" },
    { "courseCode": "CFOC303M", courseTitle: "Computer Architecture" },
    { "courseCode": "CFOC304M", courseTitle: "Programming, Data Structures And Algorithms Using Python" },
    { "courseCode": "CFOC305M", courseTitle: "Introduction to Machine Learning" },
    { "courseCode": "CFOC306M", courseTitle: "Social Networks" },
    { "courseCode": "CFOC307M", courseTitle: "Foundations to Computer Systems Design" },
    { "courseCode": "CFOC308M", courseTitle: "The Joy of Computing using Python" },
    { "courseCode": "CFOC309M", courseTitle: "Discrete Mathematics" },
    { "courseCode": "CFOC310M", courseTitle: "An Introduction to Artificial Intelligence" },
    { "courseCode": "CFOC311M", courseTitle: "User-centric Computing for Human-Computer Interaction" },
    { "courseCode": "CFOC312M", courseTitle: "Cloud Computing and Distributed Systems" },
    { "courseCode": "CFOC313M", courseTitle: "Machine Learning" },
    { "courseCode": "CFOC314M", courseTitle: "Modern Application Development" },
    { "courseCode": "CFOC315M", courseTitle: "An Introduction To Programming Through C++" },
    { "courseCode": "CFOC316M", courseTitle: "Design and Pedagogy of the Introductory Programming Course" },
    { "courseCode": "CFOC317M", courseTitle: "Quantitative Methods in Chemistry" },
    { "courseCode": "CFOC318M", courseTitle: "Basics in Inorganic Chemistry" },
    { "courseCode": "CFOC319M", courseTitle: "Ultrafast Laser Spectroscopy" },
    { "courseCode": "CFOC320M", courseTitle: "Transition Metal Organometallics in Catalysis and Biology" },
    { "courseCode": "CFOC321M", courseTitle: "Essentials of Biomolecules: Nucleic Acids and Peptides" },
    { "courseCode": "CFOC322M", courseTitle: "Fundamentals of Spectroscopy" },
    { "courseCode": "CFOC323M", courseTitle: "Advanced Chemical Thermodynamics and Kinetics" },
    { "courseCode": "CFOC324M", courseTitle: "Biochemistry" },
    { "courseCode": "CFOC325M", courseTitle: "Organometallic Chemistry" },
    { "courseCode": "CFOC326M", courseTitle: "Chemical Applications of Symmetry and Group Theory" },
    { "courseCode": "CFOC327M", courseTitle: "Basic Thermodynamics: Classical and Statistical Approaches" },
    { "courseCode": "CFOC328M", courseTitle: "Medicinal Chemistry." },
    { "courseCode": "CFOC329M", courseTitle: "Design, Technology and Innovation" },
    { "courseCode": "CFOC330M", courseTitle: "Geographic Information System" },
    { "courseCode": "CFOC331M", courseTitle: "Product Design and Innovation" },
    { "courseCode": "CFOC332M", courseTitle: "Fundamentals of Automotive Systems" },
    { "courseCode": "CFOC333M", courseTitle: "Electronics Equipment Integration and Prototype Building" },
    { "courseCode": "CFOC334M", courseTitle: "High Power Multilevel Converters-Analysis, Design and Operational Issues" },
    { "courseCode": "CFOC335M", courseTitle: "Fuzzy Sets, Logic and Systems and Applications" },
    { "courseCode": "CFOC336M", courseTitle: "Transmission Lines and Electromagnetic Waves" },
    { "courseCode": "CFOC337M", courseTitle: "Digital IC Design" },
    { "courseCode": "CFOC338M", courseTitle: "Signals and Systems" },
    { "courseCode": "CFOC339M", courseTitle: "Power Management Integrated Circuits" },
    { "courseCode": "CFOC340M", courseTitle: "DC Power Transmission Systems" },
    { "courseCode": "CFOC341M", courseTitle: "Microprocessors and Interfacing" },
    { "courseCode": "CFOC342M", courseTitle: "Design and Simulation of Power Conversion using Open Source Tools" },
    { "courseCode": "CFOC343M", courseTitle: "Integrated Circuits, MOSFETS, OP-Amps and their Applications" },
    { "courseCode": "CFOC344M", courseTitle: "Electronic Systems for Cancer Diagnosis" },
    { "courseCode": "CFOC345M", courseTitle: "Principles of Signals and Systems" },
    { "courseCode": "CFOC346M", courseTitle: "Principles of Communication Systems - I" },
    { "courseCode": "CFOC347M", courseTitle: "Principles of Digital Communication" },
    { "courseCode": "CFOC348M", courseTitle: "Electric Vehicles - Part 1" },
    { "courseCode": "CFOC349M", courseTitle: "Nonlinear Adaptive Control" },
    { "courseCode": "CFOC350M", courseTitle: "Antennas" },
    { "courseCode": "CFOC351M", courseTitle: "Multirate DSP" },
    { "courseCode": "CFOC352M", courseTitle: "Control Engineering" },
    { "courseCode": "CFOC353M", courseTitle: "Introduction to Photonics" },
    { "courseCode": "CFOC354M", courseTitle: "Microwave Integrated Circuits 2" },
    { "courseCode": "CFOC355M", courseTitle: "Analog IC Design" },
    { "courseCode": "CFOC356M", courseTitle: "Analog Circuits" },
    { "courseCode": "CFOC357M", courseTitle: "Advance Power Electronics and Control" },
    { "courseCode": "CFOC358M", courseTitle: "CMOS Digital VLSI Design" },
    { "courseCode": "CFOC359M", courseTitle: "Analog Circuits and Systems through SPICE Simulation" },
    { "courseCode": "CFOC360M", courseTitle: "Discrete Time Signal Processing" },
    { "courseCode": "CFOC361M", courseTitle: "Digital Electronic Circuits" },
    { "courseCode": "CFOC362M", courseTitle: "Fundamentals of MIMO Wireless Communication" },
    { "courseCode": "CFOC363M", courseTitle: "Spread Spectrum Communications and Jamming" },
    { "courseCode": "CFOC364M", courseTitle: "Basic Building Blocks of Microwave Engineering & Design Principles of RF and Microware filters and Amplifiers" },
    { "courseCode": "CFOC365M", courseTitle: "Evolution of Air Interface towards 5G" },
    { "courseCode": "CFOC366M", courseTitle: "Architectural Design of Digital Integrated Circuits" },
    { "courseCode": "CFOC367M", courseTitle: "Electrical Machines - II" },
    { "courseCode": "CFOC368M", courseTitle: "Medical Image Analysis" },
    { "courseCode": "CFOC369M", courseTitle: "Biomedical Signal Processing" },
    { "courseCode": "CFOC370M", courseTitle: "Microprocessors And Microcontrollers" },
    { "courseCode": "CFOC371M", courseTitle: "Recent Advances in Transmission Insulator" },
    { "courseCode": "CFOC372M", courseTitle: "VLSI Signal Processing" },
    { "courseCode": "CFOC373M", courseTitle: "Analog Electronic Circuits" },
    { "courseCode": "CFOC374M", courseTitle: "Network Analysis" },
    { "courseCode": "CFOC375M", courseTitle: "Optical Engineering" },
    { "courseCode": "CFOC376M", courseTitle: "Mathematical Methods and Techniques in Signal Processing" },
    { "courseCode": "CFOC377M", courseTitle: "A brief introduction of Micro – Sensors" },
    { "courseCode": "CFOC378M", courseTitle: "Statistical Signal Processing" },
    { "courseCode": "CFOC379M", courseTitle: "Nonlinear System Analysis" },
    { "courseCode": "CFOC380M", courseTitle: "Ethics in Engineering Practice" },
    { "courseCode": "CFOC381M", courseTitle: "Introduction to Research" },
    { "courseCode": "CFOC382M", courseTitle: "Matlab Programming for Numerical Computation" },
    { "courseCode": "CFOC383M", courseTitle: "Roadmap for Patent Creation" },
    { "courseCode": "CFOC384M", courseTitle: "Entrepreneurship Essentials" },
    { "courseCode": "CFOC385M", courseTitle: "Fuzzy Logic and Neural Networks" },
    { "courseCode": "CFOC386M", courseTitle: "Microeconomics: Theory & Applications" },
    { "courseCode": "CFOC387M", courseTitle: "Introduction to Environmental Economics" },
    { "courseCode": "CFOC388M", courseTitle: "Energy Resources, Economics and Environment" },
    { "courseCode": "CFOC389M", courseTitle: "Literary Criticism (From Plato to Leavis)" },
    { "courseCode": "CFOC390M", courseTitle: "Twentieth Century Fiction" },
    { "courseCode": "CFOC391M", courseTitle: "Effective Writing" },
    { "courseCode": "CFOC392M", courseTitle: "Strategic Trade and Protectionism - Theories and Empirics" },
    { "courseCode": "CFOC393M", courseTitle: "Introduction to Cultural Studies" },
    { "courseCode": "CFOC394M", courseTitle: "Introduction to Basic Spoken Sanskrit" },
    { "courseCode": "CFOC395M", courseTitle: "Speaking Effectively" },
    { "courseCode": "CFOC396M", courseTitle: "Soft Skill Development" },
    { "courseCode": "CFOC397M", courseTitle: "Intellectual Property" },
    { "courseCode": "CFOC398M", courseTitle: "English Language for Competitive Exams" },
    { "courseCode": "CFOC399M", courseTitle: "English Literature for Competitive Exams" },
    { "courseCode": "CFOC400M", courseTitle: "Language and Mind" },
    { "courseCode": "CFOC401M", courseTitle: "The Nineteenth-Century English Novel" },
    { "courseCode": "CFOC402M", courseTitle: "Introduction to World Literature" },
    { "courseCode": "CFOC403M", courseTitle: "Patent Drafting for Beginners" },
    { "courseCode": "CFOC404M", courseTitle: "Patent Law for Engineers and Scientists" },
    { "courseCode": "CFOC405M", courseTitle: "Economic Growth & Development" },
    { "courseCode": "CFOC406M", courseTitle: "Human Behaviour" },
    { "courseCode": "CFOC407M", courseTitle: "Introduction to Modern Indian Political Thought" },
    { "courseCode": "CFOC408M", courseTitle: "English Literature of the Romantic Period, 1798-1832" },
    { "courseCode": "CFOC409M", courseTitle: "Literature, Culture and Media" },
    { "courseCode": "CFOC410M", courseTitle: "Introduction to Brain & Behaviour" },
    { "courseCode": "CFOC411M", courseTitle: "Modern Indian Writing in Translation" },
    { "courseCode": "CFOC412M", courseTitle: "Introduction to Political Ideologies: Contexts, Ideas, and Practices" },
    { "courseCode": "CFOC413M", courseTitle: "Indian Business History" },
    { "courseCode": "CFOC414M", courseTitle: "German - II" },
    { "courseCode": "CFOC415M", courseTitle: "German - 1" },
    { "courseCode": "CFOC416M", courseTitle: "Feminism: Concepts and Theories" },
    { "courseCode": "CFOC417M", courseTitle: "An Introduction to Smooth Manifolds" },
    { "courseCode": "CFOC418M", courseTitle: "Measure Theory" },
    { "courseCode": "CFOC419M", courseTitle: "Basic Real Analysis" },
    { "courseCode": "CFOC420M", courseTitle: "Probabilistic Methods in PDE" },
    { "courseCode": "CFOC421M", courseTitle: "Graph Theory" },
    { "courseCode": "CFOC422M", courseTitle: "Transform Calculus and its applications in Differential Equations" },
    { "courseCode": "CFOC423M", courseTitle: "Integral and Vector Calculus" },
    { "courseCode": "CFOC424M", courseTitle: "Basic Linear Algebra" },
    { "courseCode": "CFOC425M", courseTitle: "Introduction to Rings And Fields" },
    { "courseCode": "CFOC426M", courseTitle: "Numerical Methods: Finite Difference Approach" },
    { "courseCode": "CFOC427M", courseTitle: "Numerical Linear Algebra" },
    { "courseCode": "CFOC428M", courseTitle: "Ordinary and Partial Differential Equations and Applications" },
    { "courseCode": "CFOC429M", courseTitle: "Advanced Engineering Mathematics" },
    { "courseCode": "CFOC430M", courseTitle: "Mathematical Methods and its Applications" },
    { "courseCode": "CFOC431M", courseTitle: "Multivariable Calculus" },
    { "courseCode": "CFOC432M", courseTitle: "Chaotic Dynamical System" },
    { "courseCode": "CFOC433M", courseTitle: "Engineering Mathematics II" },
    { "courseCode": "CFOC434M", courseTitle: "Advanced Probability Theory" },
    { "courseCode": "CFOC435M", courseTitle: "Statistical Inference" },
    { "courseCode": "CFOC436M", courseTitle: "Introduction to Algebraic Geometry and Commutative Algebra" },
    { "courseCode": "CFOC437M", courseTitle: "Linear Algebra" },
    { "courseCode": "CFOC438M", courseTitle: "Introduction to Probability and Statistics" },
    { "courseCode": "CFOC439M", courseTitle: "Descriptive Statistics with R Software" },
    { "courseCode": "CFOC440M", courseTitle: "Engineering Mechanics - Statics and Dynamics" },
    { "courseCode": "CFOC441M", courseTitle: "Experimental Stress Analysis" },
    { "courseCode": "CFOC442M", courseTitle: "Robotics and Control: Theory and Practice" },
    { "courseCode": "CFOC443M", courseTitle: "Computational Fluid Dynamics for Incompressible Flows" },
    { "courseCode": "CFOC444M", courseTitle: "Experimental Methods in Fluid Mechanics" },
    { "courseCode": "CFOC445M", courseTitle: "Foundations of Computational Materials Modelling" },
    { "courseCode": "CFOC446M", courseTitle: "Acoustic Materials and Metamaterials" },
    { "courseCode": "CFOC447M", courseTitle: "Power Plant Engineering" },
    { "courseCode": "CFOC448M", courseTitle: "Applied Ergonomics" },
    { "courseCode": "CFOC449M", courseTitle: "Product Design and Manufacturing" },
    { "courseCode": "CFOC450M", courseTitle: "Manufacturing Process Technology I & II" },
    { "courseCode": "CFOC451M", courseTitle: "Introduction To Mechanical Micro Machining" },
    { "courseCode": "CFOC452M", courseTitle: "Non Traditional Abrasive Machining Processes Ultrasonic, Abrasive Jet and Abrasive Water Jet Machining" },
    { "courseCode": "CFOC453M", courseTitle: "Gear And Gear Unit Design: Theory And Practice" },
    { "courseCode": "CFOC454M", courseTitle: "Conduction and Convection Heat Transfer" },
    { "courseCode": "CFOC455M", courseTitle: "Laws of Thermodynamics" },
    { "courseCode": "CFOC456M", courseTitle: "Kinematics of Mechanisms and Machines" },
    { "courseCode": "CFOC457M", courseTitle: "Introduction To Fluid Mechanics" },
    { "courseCode": "CFOC458M", courseTitle: "Fundamental of Welding Science and Technology" },
    { "courseCode": "CFOC459M", courseTitle: "Introduction to Abrasive Machining and Finishing Processes" },
    { "courseCode": "CFOC460M", courseTitle: "Automatic Control" },
    { "courseCode": "CFOC461M", courseTitle: "Inspection and Quality Control in Manufacturing" },
    { "courseCode": "CFOC462M", courseTitle: "Diffusion in Multicomponent Solids" },
    { "courseCode": "CFOC463M", courseTitle: "Processing of Polymers and Polymer Composites" },
    { "courseCode": "CFOC464M", courseTitle: "Operations Management" },
    { "courseCode": "CFOC465M", courseTitle: "Convective Heat Transfer" },
    { "courseCode": "CFOC466M", courseTitle: "Two phase flow and heat transfer" },
    { "courseCode": "CFOC467M", courseTitle: "Steam and Gas Power Systems" },
    { "courseCode": "CFOC468M", courseTitle: "Principles of Casting Technology" },
    { "courseCode": "CFOC469M", courseTitle: "Financial Mathematics" },
    { "courseCode": "CFOC470M", courseTitle: "Modelling and Simulation of Dynamic Systems" },
    { "courseCode": "CFOC471M", courseTitle: "Fundamentals of combustion for propulsion" },
    { "courseCode": "CFOC472M", courseTitle: "Industrial Automation And Control" },
    { "courseCode": "CFOC473M", courseTitle: "Fundamentals of Nuclear Power Generation" },
    { "courseCode": "CFOC474M", courseTitle: "Mechanics of Machining" },
    { "courseCode": "CFOC475M", courseTitle: "IC Engines and Gas Turbines" },
    { "courseCode": "CFOC476M", courseTitle: "Principles of Industrial Engineering" },
    { "courseCode": "CFOC477M", courseTitle: "Computer Integrated Manufacturing" },
    { "courseCode": "CFOC478M", courseTitle: "Machining Science" },
    { "courseCode": "CFOC479M", courseTitle: "Introduction to Stochastic Processes" },
    { "courseCode": "CFOC480M", courseTitle: "Introduction to System Dynamics Modeling" },
    { "courseCode": "CFOC481M", courseTitle: "Management of New Products and Services" },
    { "courseCode": "CFOC482M", courseTitle: "Integrated Marketing Management" },
    { "courseCode": "CFOC483M", courseTitle: "Simulation of Business Systems: An Applied Approach" },
    { "courseCode": "CFOC484M", courseTitle: "Production and Operation Management" },
    { "courseCode": "CFOC485M", courseTitle: "Services Marketing: Integrating People, Technology, Strategy" },
    { "courseCode": "CFOC486M", courseTitle: "Managerial Skills for Interpersonal Dynamics" },
    { "courseCode": "CFOC487M", courseTitle: "Financial Institutions and Markets" },
    { "courseCode": "CFOC488M", courseTitle: "Business Analytics For Management Decision" },
    { "courseCode": "CFOC489M", courseTitle: "Services Marketing: A Practical Approach" },
    { "courseCode": "CFOC490M", courseTitle: "Sales and Distribution Management" },
    { "courseCode": "CFOC491M", courseTitle: "Principles of Human Resource Management" },
    { "courseCode": "CFOC492M", courseTitle: "Managing change in organizations" },
    { "courseCode": "CFOC493M", courseTitle: "Management of Inventory Systems" },
    { "courseCode": "CFOC494M", courseTitle: "Quality Design And Control" },
    { "courseCode": "CFOC495M", courseTitle: "Foundation Course in Managerial Economics" },
    { "courseCode": "CFOC496M", courseTitle: "Engineering Econometrics" },
    { "courseCode": "CFOC497M", courseTitle: "Financial Statement Analysis and Reporting" },
    { "courseCode": "CFOC498M", courseTitle: "Business Statistics" },
    { "courseCode": "CFOC499M", courseTitle: "Global Marketing Management" },
    { "courseCode": "CFOC500M", courseTitle: "Marketing Research and Analysis - II" },
    { "courseCode": "CFOC501M", courseTitle: "Infrastructure Planning and Managements" },
    { "courseCode": "CFOC502M", courseTitle: "Modelling and Analytics for Supply Chain Management" },
    { "courseCode": "CFOC503M", courseTitle: "Marketing Analytics" },
    { "courseCode": "CFOC504M", courseTitle: "Financial Management For Managers" },
    { "courseCode": "CFOC505M", courseTitle: "Management of Commercial Banking" },
    { "courseCode": "CFOC506M", courseTitle: "Behavioral and Personal Finance" },
    { "courseCode": "CFOC507M", courseTitle: "Total Quality Management - 1" },
    { "courseCode": "CFOC508M", courseTitle: "Entrepreneurship" },
    { "courseCode": "CFOC509M", courseTitle: "Modeling of Tundish Steelmaking Process in Continuous Casting" },
    { "courseCode": "CFOC510M", courseTitle: "Fundamentals of Electronic Materials and Devices" },
    { "courseCode": "CFOC511M", courseTitle: "Introduction to Materials Science and Engineering" },
    { "courseCode": "CFOC512M", courseTitle: "Corrosion - Part I" },
    { "courseCode": "CFOC513M", courseTitle: "Solar Photovoltaics: Principles, Technologies and Materials" },
    { "courseCode": "CFOC514M", courseTitle: "Welding Processes" },
    { "courseCode": "CFOC515M", courseTitle: "Theory and Practice of Non Destructive Testing" },
    { "courseCode": "CFOC516M", courseTitle: "Steel Quality: Role of Secondary Refining and Continuous Casting" },
    { "courseCode": "CFOC517M", courseTitle: "Materials Science and Engineering" },
    { "courseCode": "CFOC518M", courseTitle: "Surface Engineering of Nanomaterials" },
    { "courseCode": "CFOC519M", courseTitle: "Dealing with Materials Data: Collection, Analysis and Interpretation" },
    { "courseCode": "CFOC520M", courseTitle: "Friction and Wear of Materials: Principle and Case Studies" },
    { "courseCode": "CFOC521M", courseTitle: "Material Characterization" },
    { "courseCode": "CFOC522M", courseTitle: "Offshore Structures Under Special Environmental Loads Including Fire Resistance" },
    { "courseCode": "CFOC523M", courseTitle: "Physics of Biological Systems" },
    { "courseCode": "CFOC524M", courseTitle: "Group Theory methods in Physics" },
    { "courseCode": "CFOC525M", courseTitle: "Experimental Physics - II" },
    { "courseCode": "CFOC526M", courseTitle: "Quantum Mechanics I" },
    { "courseCode": "CFOC527M", courseTitle: "A Brief Course on Superconductivity" },
    { "courseCode": "CFOC528M", courseTitle: "Fiber Optics" },
    { "courseCode": "CFOC529M", courseTitle: "Electromagnetism" },
    { "courseCode": "CFOC530M", courseTitle: "Experimental Physics III" },
    { "courseCode": "CFOC531M", courseTitle: "Electronic Theory of Solids" },
    { "courseCode": "CFOC532M", courseTitle: "Introduction to Atmospheric and Space Sciences" },
    { "courseCode": "CFOC533M", courseTitle: "Optical Sensors" },
    { "courseCode": "CFOC534M", courseTitle: "Evaluation of Textiles Materials" },
    { "courseCode": "CFOC535M", courseTitle: "Advanced Textile Printing Technology" },
    { "courseCode": "CFOC536M", courseTitle: "Textured Yarn Technology" },
    { "courseCode": "CFOC537M", courseTitle: "Theory of Yarn Structure" },
    { "courseCode": "CFOC538M", courseTitle: "Testing of Functional and Technical Textiles" },
    { "courseCode": "CFOC539M", courseTitle: "Applied Optimization for Wireless, Machine Learning, Big Data" },
    { "courseCode": "CFOC540M", courseTitle: "Deep Learning for Computer Vision" },
    { "courseCode": "CFOC541M", courseTitle: "Deep Learning for Visual Computing" },
    { "courseCode": "CFOC542M", courseTitle: "Principles of Compiler Design" },
    { "courseCode": "CFOC543M", courseTitle: "International Business" },
    { "courseCode": "CFOC544M", courseTitle: "Learning Analytics Tools" },
    { "courseCode": "CFOC545M", courseTitle: "Advanced IoT Applications" },
    { "courseCode": "CFOC546M", courseTitle: "Algorithms for Big Data" },
    { "courseCode": "CFOC547M", courseTitle: "Decision Making Using Financial Accounting" },
    { "courseCode": "CFOC548M", courseTitle: "Introduction on Intellectual Property to Engineers and Technologists" },
    { "courseCode": "CFOC549M", courseTitle: "Introduction to Quantum Computing: Quantum Algorithms and Qiskit" },
    { "courseCode": "CFOC550M", courseTitle: "Numerical Analysis" },
    { "courseCode": "CFOC551M", courseTitle: "Quantum Technology and Quantum Phenomena in Macroscopic Systems" },
    { "courseCode": "CFOC552M", courseTitle: "Electrochemical Impedance Spectroscopy" },
    { "courseCode": "CFOC553M", courseTitle: "Carbon Materials and Manufacturing" },
    { "courseCode": "CFOC554M", courseTitle: "Electronic Packaging and Manufacturing" },
    { "courseCode": "CFOC555M", courseTitle: "Finite Element Method" },
    { "courseCode": "CFOC556M", courseTitle: "Physics of Materials" },
    { "courseCode": "CFOC557M", courseTitle: "X-ray Crystallography and Diffraction" },
    { "courseCode": "CFOC558M", courseTitle: "Solar Photovoltaics Fundamentals, Technology and Applications" },
    { "courseCode": "CFOC559M", courseTitle: "Design of Photovoltaic Systems" },
    { "courseCode": "CFOC560M", courseTitle: "Fundamentals of Micro and Nanofabrication" },
    { "courseCode": "CFOC561M", courseTitle: "Biomedical Nanotechnology" },
    { "courseCode": "CFOC562M", courseTitle: "Design and Analysis of VLSI Subsystems" },
    { "courseCode": "CFOC563M", courseTitle: "Physics of Nanoscale Devices" },
    { "courseCode": "CFOC564M", courseTitle: "Photonic Integrated Circuit" },
    { "courseCode": "CFOC565M", courseTitle: "Technologies for Clean and Renewable Energy Production" },
    { "courseCode": "CFOC566M", courseTitle: "Elements of Solar Energy Conversion" },
    { "courseCode": "CFOC567M", courseTitle: "Physics of Renewable Energy Systems" },
    { "courseCode": "CFOC568M", courseTitle: "Structural Analysis of Nanomaterials" },
    { "courseCode": "CFOC569M", courseTitle: "Computational Approach to Materials Science and Engineering" },
    { "courseCode": "CFOC570M", courseTitle: "Public Speaking" },
    { "courseCode": "CFOC571M", courseTitle: "Introduction To CFD" },
    { "courseCode": "CFOC572M", courseTitle: "Dairy And Food Process And Products Technology" },
    { "courseCode": "CFOC573M", courseTitle: "Fundamentals Of Food Process Engineering" },
    { "courseCode": "CFOC574M", courseTitle: "Micro Irrigation Engineering" },
    { "courseCode": "CFOC575M", courseTitle: "Wildlife Ecology" },
    { "courseCode": "CFOC576M", courseTitle: "Integrated Waste Management For A Smart City" },
    { "courseCode": "CFOC577M", courseTitle: "Introduction To Multimodal Urban Transportation Systems (MUTS)" },
    { "courseCode": "CFOC578M", courseTitle: "Wastewater Treatment And Recycling" },
    { "courseCode": "CFOC579M", courseTitle: "Structural Geology" },
    { "courseCode": "CFOC580M", courseTitle: "Real-Time Systems" },
    { "courseCode": "CFOC581M", courseTitle: "Algorithmic Game Theory" },
    { "courseCode": "CFOC582M", courseTitle: "Computational Number Theory and Algebra" },
    { "courseCode": "CFOC583M", courseTitle: "Power System Protection" },
    { "courseCode": "CFOC585M", courseTitle: "Great Experiments In Psychology" },
    { "courseCode": "CFOC586M", courseTitle: "Spoken Sanskrit: Basic and Intermediate Levels" },
    { "courseCode": "CFOC587M", courseTitle: "Economics of Banking and Finance Markets" },
    { "courseCode": "CFOC588M", courseTitle: "Concepts Of Thermodynamics" },
    { "courseCode": "CFOC589M", courseTitle: "Engineering Drawing And Computer Graphics" },
    { "courseCode": "CFOC590M", courseTitle: "Management Information System" },
    { "courseCode": "CFOC591M", courseTitle: "Principles Of Management" },
    { "courseCode": "CFOC592M", courseTitle: "Stress Management" },
    { "courseCode": "CFOC593M", courseTitle: "Corporate Finance" },
    { "courseCode": "CFOC594M", courseTitle: "Customer Relationship Management" },
    { "courseCode": "CFOC595M", courseTitle: "Urbanization and Environment" },
    { "courseCode": "CFOC596M", courseTitle: "Digital Speech Processing" },
    { "courseCode": "CFOC597M", courseTitle: "Globalization And Culture" },
    { "courseCode": "CFOC598M", courseTitle: "Elements of Visual Representation" },
    { "courseCode": "CFOC599M", courseTitle: "Leadership and Team Effectiveness" },
    { "courseCode": "CFOC600M", courseTitle: "Data Analysis for Biologists" },
    { "courseCode": "CFOC601M", courseTitle: "Advance Course in Social Psychology" },
    { "courseCode": "CFOC602M", courseTitle: "Product and Brand Management" },
    { "courseCode": "CFOC603M", courseTitle: "Quantitative Investment Management" },
    { "courseCode": "CFOC604M", courseTitle: "Entrepreneurship and IP Strategy" },
    { "courseCode": "CFOC605M", courseTitle: "Sensor Technologies: Physics, Fabrication, and Circuits" },
    { "courseCode": "CFOC606M", courseTitle: "Ecology and Environment" },
    { "courseCode": "CFOC607M", courseTitle: "Analog VLSI Design" },
    { "courseCode": "CFOC608M", courseTitle: "The Science of Happiness and Wellbeing-" },
    { "courseCode": "CFOC609M", courseTitle: "Introduction to Basic Spoken Sanskrit and Intermediate Level of Spoken Sanskrit" },
    { "courseCode": "CFOC610M", courseTitle: "Advanced Algorithmic Trading and Portfolio Management" },
    { "courseCode": "CFOC611M", courseTitle: "Advanced Quantum Mechanics with Applications" },
    { "courseCode": "CFOC612M", courseTitle: "Business Fundamentals for Entrepreneurs" },
    { "courseCode": "CFOC613M", courseTitle: "C-Based VLSI Design" },
    { "courseCode": "CFOC614M", courseTitle: "The Popular Gothic Novel" },
    { "courseCode": "CFOC615M", courseTitle: "Introduction To Biomimicry" },
    { "courseCode": "CFOC616M", courseTitle: "Applied Linguistics" },
    { "courseCode": "CFOC617M", courseTitle: "Gender and Literature" },
    { "courseCode": "CFOC618M", courseTitle: "Developing Soft Skills and Personality" },
    { "courseCode": "CFOC619M", courseTitle: "Corporate Finance_2" },
    { "courseCode": "CFOC620M", courseTitle: "Architectural Acoustics" },
    { "courseCode": "CFOC621M", courseTitle: "An Introduction to Indian Literary Theory" },
    { "courseCode": "CFOC622M", courseTitle: "Indian Art: Materials, Techniques and Artistic Practices" },
    { "courseCode": "CFOC623M", courseTitle: "Space Flight Mechanics" },
    { "courseCode": "CFOC624M", courseTitle: "Industrial Safety Engineering" },
    { "courseCode": "CFOC625M", courseTitle: "Advanced Thermodynamics and Combustion" },
    { "courseCode": "CFOC626M", courseTitle: "Postmodernism in Literature" },
    { "courseCode": "CFOC627M", courseTitle: "Natural Language Processing" },
    { "courseCode": "CFOC628M", courseTitle: "Appreciating Carnatic Music" },
    { "courseCode": "CFOC629M", courseTitle: "Body language: Key to Professional Success" },
    { "courseCode": "CFOC630M", courseTitle: "Business To Business Marketing" },
    { "courseCode": "CFOC631M", courseTitle: "Conservation Geography" },
    { "courseCode": "CFOC632M", courseTitle: "Enclosure design of Electronics equipment" },
    { "courseCode": "CFOC633M", courseTitle: "Environment And Development" },
    { "courseCode": "CFOC634M", courseTitle: "Introduction to Aerospace Engineering" },
    { "courseCode": "CFOC635M", courseTitle: "Operations And Supply Chain Management" },
    { "courseCode": "CFOC636M", courseTitle: "Programming in modern c++" },
    { "courseCode": "CFOC637M", courseTitle: "Psychology Of Learning" },
    { "courseCode": "CFOC638M", courseTitle: "Urban Utilities Planning: Water Supply, Sanitation And Drainage" },
    { "courseCode": "CFOC639M", courseTitle: "Research Methodology" },
    { "courseCode": "CFOC640M", courseTitle: "Communication Networks" },
    { "courseCode": "CFOC641M", courseTitle: "Aircraft Design" },
    { "courseCode": "CFOC642M", courseTitle: "Conservation Economics" },
    { "courseCode": "CFOC643M", courseTitle: "Cryogenic Hydrogen Technology" },
    { "courseCode": "CFOC644M", courseTitle: "Explosions and Safety" },
    { "courseCode": "CFOC645M", courseTitle: "Financial Accounting" },
    { "courseCode": "CFOC646M", courseTitle: "Philosophy and Critical Thinking" },
    { "courseCode": "CFOC647M", courseTitle: "Air pollution and Control" },
    { "courseCode": "CFOC648M", courseTitle: "Centre-State Relations in India" },
    { "courseCode": "CFOC649M", courseTitle: "Energy Resources, Economics, and Sustainability" },
    { "courseCode": "CFOC650M", courseTitle: "Human Physiology" },
    { "courseCode": "CFOC651M", courseTitle: "Psychology of Stress, Health and Wellbeing-" },
    { "courseCode": "CFOC652M", courseTitle: "Signal Processing Techniques and its Applications" },
    { "courseCode": "CFOC653M", courseTitle: "Strength & Conditioning for the Indian Population" },
    { "courseCode": "CFOC654M", courseTitle: "The Evolution of the Earth and Life" },
    { "courseCode": "CFOC655M", courseTitle: "United Nations Sustainable Development Goals (UN SDGs)" },
    { "courseCode": "CFOC656M", courseTitle: "Usability Engineering" },
    { "courseCode": "CFOC658M", courseTitle: "Design Practice - II" },
    { "courseCode": "CFOC659M", courseTitle: "Essentials of Data Science With R Software - 1: Probability and Statistical Inference" },
    { "courseCode": "CFOC660M", courseTitle: "Applied Linear Algebra in Al and ML" },
    { "courseCode": "BCHY102N", courseTitle: "Environmental Sciences" },
    { "courseCode": "BCSE101N", courseTitle: "Introduction to Engineering" },
    { "courseCode": "BEXC100N", courseTitle: "Extra curricular activities" },
    { "courseCode": "BHUM101N", courseTitle: "Ethics and Values" },
    { "courseCode": "BSSC101N", courseTitle: "Essence of Traditional Knowledge" },
    { "courseCode": "BSSC102N", courseTitle: "Indian Constitution" },
    { "courseCode": "BENG101N", courseTitle: "Effective English Cornmunication" }
];

export default allCourses;